# Generated by Django 3.1.5 on 2021-01-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210105_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
