pdto.setEnergy((int)(pdto.getEnergy()*percent/100.0));
pdto.setCarbo_LB((int)(pdto.getCarbo_LB()*percent/100.0));
pdto.setCarbo_IA((int)(pdto.getCarbo_IA()*percent/100.0));
pdto.setCarbo_UB((int)(pdto.getCarbo_UB()*percent/100.0));
pdto.setFiber_LB((int)(pdto.getFiber_LB()*percent/100.0));
pdto.setFiber_IA((int)(pdto.getFiber_IA()*percent/100.0)); 
pdto.setFiber_UB((int)(pdto.getFiber_UB()*percent/100.0));
pdto.setLipid_LB((int)(pdto.getLipid_LB()*percent/100.0));
pdto.setLipid_IA((int)(pdto.getLipid_IA()*percent/100.0)); 
pdto.setLipid_UB((int)(pdto.getLipid_UB()*percent/100.0));
pdto.setLinoleic_acid_LB_acid_LB((int)(pdto.getLinoleic_acid_LB()*percent/100.0));
pdto.setLinoleic_acid_IA_acid_IA((int)(pdto.getLinoleic_acid_IA()*percent/100.0));
pdto.setLinoleic_acid_UB_acid_UB((int)(pdto.getLinoleic_acid_UB()*percent/100.0));
pdto.setA_linoleic_acid_LBic_acid_LB((int)(pdto.getA_linoleic_acid_LB()*percent/100.0));
pdto.setA_linoleic_acid_IAic_acid_IA((int)(pdto.getA_linoleic_acid_IA()*percent/100.0));
pdto.setA_linoleic_acid_UBic_acid_UB((int)(pdto.getA_linoleic_acid_UB()*percent/100.0));
pdto.setPro_LB((int)(pdto.getPro_LB()*percent/100.0));
pdto.setPro_IA((int)(pdto.getPro_IA()*percent/100.0));
pdto.setPro_UB((int)(pdto.getPro_UB()*percent/100.0));
pdto.setVitA_LB ((int)(pdto.getVitA_LB()*percent/100.0));
pdto.setVitA_IA ((int)(pdto.getVitA_IA()*percent/100.0));
pdto.setVitA_UB ((int)(pdto.getVitA_UB()*percent/100.0));
pdto.setVitD_LB ((int)(pdto.getVitD_LB()*percent/100.0));
pdto.setVitD_IA ((int)(pdto.getVitD_IA()*percent/100.0));
pdto.setVitD_UB ((int)(pdto.getVitD_UB()*percent/100.0));
pdto.setVitE_LB ((int)(pdto.getVitE_LB()*percent/100.0));
pdto.setVitE_IA ((int)(pdto.getVitE_IA()*percent/100.0));
pdto.setVitE_UB ((int)(pdto.getVitE_UB()*percent/100.0));
pdto.setVitK_LB ((int)(pdto.getVitK_LB()*percent/100.0));
pdto.setVitK_IA ((int)(pdto.getVitK_IA()*percent/100.0));
pdto.setVitK_UB ((int)(pdto.getVitK_UB()*percent/100.0));
pdto.setVitC_LB ((int)(pdto.getVitC_LB()*percent/100.0));
pdto.setVitC_IA ((int)(pdto.getVitC_IA()*percent/100.0));
pdto.setVitC_UB ((int)(pdto.getVitC_UB()*percent/100.0));
pdto.setThia_LB ((int)(pdto.getThia_LB()*percent/100.0));
pdto.setThia_IA ((int)(pdto.getThia_IA()*percent/100.0));
pdto.setThia_UB ((int)(pdto.getThia_UB()*percent/100.0));
pdto.setRibo_LB ((int)(pdto.getRibo_LB()*percent/100.0));
pdto.setRibo_IA ((int)(pdto.getRibo_IA()*percent/100.0));
pdto.setRibo_UB ((int)(pdto.getRibo_UB()*percent/100.0));
pdto.setVitB6_LB((int)(pdto.getVitB6_LB()*percent/100.0));
pdto.setVitB6_IA((int)(pdto.getVitB6_IA()*percent/100.0));
pdto.setVitB6_UB((int)(pdto.getVitB6_UB()*percent/100.0));
pdto.setFolic_LB((int)(pdto.getFolic_LB()*percent/100.0));
pdto.setFolic_IA((int)(pdto.getFolic_IA()*percent/100.0));
pdto.setFolic_UB((int)(pdto.getFolic_UB()*percent/100.0));
pdto.setVitB12_LB((int)(pdto.getVitB12_LB()*percent/100.0));
pdto.setVitB12_IA((int)(pdto.getVitB12_IA()*percent/100.0));
pdto.setVitB12_UB((int)(pdto.getVitB12_UB()*percent/100.0));
pdto.setPanto_LB((int)(pdto.getPanto_LB()*percent/100.0));
pdto.setPanto_IA((int)(pdto.getPanto_IA()*percent/100.0));
pdto.setPanto_UB((int)(pdto.getPanto_UB()*percent/100.0));
pdto.setBio_LB((int)(pdto.getBio_LB()*percent/100.0));
pdto.setBio_IA((int)(pdto.getBio_IA()*percent/100.0));
pdto.setBio_UB((int)(pdto.getBio_UB()*percent/100.0));
pdto.setCa_LB((int)(pdto.getCa_LB()*percent/100.0));
pdto.setCa_IA((int)(pdto.getCa_IA()*percent/100.0));
pdto.setCa_UB((int)(pdto.getCa_UB()*percent/100.0));
pdto.setP_LB((int)(pdto.getP_LB()*percent/100.0));
pdto.setP_IA((int)(pdto.getP_IA()*percent/100.0));
pdto.setP_UB((int)(pdto.getP_UB()*percent/100.0));
pdto.setNa_LB((int)(pdto.getNa_LB()*percent/100.0));
pdto.setNa_IA((int)(pdto.getNa_IA()*percent/100.0));
pdto.setNa_UB((int)(pdto.getNa_UB()*percent/100.0));
pdto.setK_LB((int)(pdto.getK_LB()*percent/100.0));
pdto.setK_IA((int)(pdto.getK_IA()*percent/100.0));
pdto.setK_UB((int)(pdto.getK_UB()*percent/100.0));
pdto.setMg_LB((int)(pdto.getMg_LB()*percent/100.0));
pdto.setMg_IA((int)(pdto.getMg_IA()*percent/100.0));
pdto.setMg_UB((int)(pdto.getMg_UB()*percent/100.0));
pdto.setFe_LB((int)(pdto.getFe_LB()*percent/100.0));
pdto.setFe_IA((int)(pdto.getFe_IA()*percent/100.0));
pdto.setFe_UB((int)(pdto.getFe_UB()*percent/100.0));
pdto.setZn_LB((int)(pdto.getZn_LB()*percent/100.0));
pdto.setZn_IA((int)(pdto.getZn_IA()*percent/100.0));
pdto.setZn_UB((int)(pdto.getZn_UB()*percent/100.0));
pdto.setCu_LB((int)(pdto.getCu_LB()*percent/100.0));
pdto.setCu_IA((int)(pdto.getCu_IA()*percent/100.0));
pdto.setCu_UB((int)(pdto.getCu_UB()*percent/100.0));

